---
    # defaults file for docker
    
    audit_master:
          - { name: auditoria }
          - { name: auditoria_slave }
               
    audit_nodes:
      - { name: jenkins }
      - { name: gitlab-ce }
    
     
    