- hosts: all
  become: true

  tasks:
    - name: instalando o pacote do rsyslog-ng
      apt:
        name: syslog-ng
        state: present
      with_items: "{{audit_master}}"
      when: {{ item.isMaster == true }}